import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { BUSINESSES } from "@/lib/businesses";
import { getBusiness } from "@/lib/businesses";

const WEEKLY_TOOLS = ["keywords", "blog", "guest", "sites", "outreach"];

async function generateContent(businessSlug: string, type: string, extra = ""): Promise<string> {
  const res = await fetch(`${process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"}/api/generate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ businessSlug, type, extra }),
  });
  const data = await res.json();
  return data.content ?? `Error generating ${type}`;
}

function buildEmailHtml(biz: ReturnType<typeof getBusiness>, results: Record<string, string>): string {
  const sections = WEEKLY_TOOLS.map(tool => {
    const labels: Record<string, string> = {
      keywords: "🎯 Target Keywords",
      blog: "📝 Blog Post (publish to your site)",
      guest: "🌐 Guest Post (pitch to other sites)",
      sites: "🔗 Target Sites for Backlinks",
      outreach: "📧 Outreach Emails (send these this week)",
    };
    return `
      <div style="margin-bottom:40px;border-left:4px solid #7c3aed;padding-left:20px;">
        <h2 style="color:#7c3aed;margin:0 0 16px;">${labels[tool]}</h2>
        <pre style="white-space:pre-wrap;font-family:Georgia,serif;font-size:14px;line-height:1.7;color:#1e293b;background:#f8fafc;padding:20px;border-radius:8px;">${results[tool]}</pre>
      </div>
    `;
  }).join("");

  return `
    <!DOCTYPE html>
    <html>
    <body style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:40px 20px;color:#1e293b;">
      <div style="background:#0d0f1a;padding:24px 32px;border-radius:12px;margin-bottom:32px;">
        <h1 style="color:#fff;margin:0;font-size:24px;">GrowthDesk Weekly Report</h1>
        <p style="color:#a0a9cc;margin:8px 0 0;">${biz!.name} — ${new Date().toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}</p>
      </div>
      <p style="color:#475569;font-size:15px;line-height:1.6;">
        Here's your weekly SEO content for <strong>${biz!.name}</strong>.
        Use the blog post on your site, send the outreach emails, and pitch the guest post to the target sites listed.
      </p>
      ${sections}
      <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:20px;margin-top:32px;">
        <h3 style="color:#15803d;margin:0 0 8px;">✅ This week's SEO checklist</h3>
        <ul style="color:#166534;line-height:2;margin:0;padding-left:20px;">
          <li>Publish the blog post on ${biz!.url}</li>
          <li>Send the 3 outreach emails to the target sites</li>
          <li>Submit to 3 new UK directories (see GrowthDesk → UK Directories)</li>
          <li>Post one update to your Google Business profile</li>
        </ul>
      </div>
      <p style="color:#94a3b8;font-size:12px;margin-top:40px;text-align:center;">
        Generated by GrowthDesk · Powered by AI
      </p>
    </body>
    </html>
  `;
}

export async function POST(req: NextRequest) {
  const { businessSlug, toEmail, secret } = await req.json();

  // Protect cron endpoint
  if (secret !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const biz = getBusiness(businessSlug);
  if (!biz) return NextResponse.json({ error: "Business not found" }, { status: 400 });

  // Generate all weekly tools in parallel
  const [keywords, blog, guest, sites, outreach] = await Promise.all(
    WEEKLY_TOOLS.map(tool => generateContent(businessSlug, tool))
  );

  const results = { keywords, blog, guest, sites, outreach };

  // Send email
  const resend = new Resend(process.env.RESEND_API_KEY);
  await resend.emails.send({
    from: "GrowthDesk <reports@growthdesk.co.uk>",
    to: toEmail,
    subject: `📈 Weekly SEO Report — ${biz.name} — ${new Date().toLocaleDateString("en-GB")}`,
    html: buildEmailHtml(biz, results),
  });

  return NextResponse.json({ success: true, businessSlug });
}

// Vercel Cron handler — runs every Monday at 8am
export async function GET(req: NextRequest) {
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const toEmail = process.env.REPORT_EMAIL ?? "info@tattonprojects.co.uk";
  const results = [];

  for (const biz of BUSINESSES) {
    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_APP_URL}/api/auto-run`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ businessSlug: biz.slug, toEmail, secret: process.env.CRON_SECRET }),
      });
      const data = await res.json();
      results.push({ biz: biz.slug, ...data });
    } catch (e) {
      results.push({ biz: biz.slug, error: String(e) });
    }
  }

  return NextResponse.json({ results });
}
